# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install gdal
        run: |
          sudo apt-get update
          sudo apt-get -y install gdal-bin libgdal-dev build-essential
          pip install --upgrade pip
          pip install --no-cache-dir setuptools==57.4.0
          pip install --no-cache-dir GDAL==3.2.2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout mojxml2geojson
        uses: actions/checkout@v3
        with:
          repository: JDA-DM/mojxml2geojson
          path: ./mojxml2geojson
      - name: Get xml filename without extension
        run: echo "XML_FILENAME=$(ls data/*.xml | xargs -i basename {} .xml)" >> $GITHUB_ENV
      - name: Convert xml to geojson
        run: |
          pip install .
          mojxml2geojson ../data/${{ env.XML_FILENAME }}.xml
        working-directory: ./mojxml2geojson
      - name: Convert GeoJSON file
        run: |
          node convert.js data/${{ env.XML_FILENAME }}.geojson
      - name: Move data.geojson
        run: mv data.geojson dist/
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
